AllCops:
  TargetRubyVersion: 3.2.0
  TargetRailsVersion: 7.0.8
  Exclude:
    - "vendor/**/*" # rubocop config/default.yml
    - "db/**/*"
    - "node_modules/**/*"
    - "app/channels/**/*"
    - "config/**/*"
    - "bin/**/*"
    - "public/**/*"
    - "tmp/**/*"
    - "log/**/*"

Metrics/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes

# Assignment: 変数への代入
# Branch: メソッド呼び出し
# Condition: 条件文
# 上記項目をRubocopが計算して基準値を超えると警告を出す（上記頭文字をとって'Abc'）
Metrics/AbcSize:
  Max: 50

# メソッドの中身が複雑になっていないか、Rubocopが計算して基準値を超えると警告を出す
Metrics/PerceivedComplexity:
  Max: 8

# 循環的複雑度が高すぎないかをチェック（ifやforなどを1メソッド内で使いすぎている）
Metrics/CyclomaticComplexity:
  Max: 10

# メソッドの行数が多すぎないかをチェック
Metrics/MethodLength:
  CountComments: false
  Max: 30

# ネストが深すぎないかをチェック（if文のネストもチェック）
Metrics/BlockNesting:
  Max: 5

# クラスの行数をチェック
Metrics/ClassLength:
  CountComments: false
  Max: 300

# クラス内にクラスが定義されていないかチェック（無効）
Style/ClassAndModuleChildren:
  Enabled: false

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# クラスやモジュール定義前に、それらの説明書きがあるかをチェック（無効）
Style/Documentation:
  Enabled: false

# ％i（）構文を使用していないシンボルで構成される配列リテラルをチェック（無効）
Style/SymbolArray:
  Enabled: false

# 文字列に値が代入されて変わっていないかチェック（無効）
Style/FrozenStringLiteralComment:
  Enabled: false

Naming/VariableNumber:
  Enabled: false